# Generated by Django 4.2.5 on 2023-09-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent_One',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name1', models.CharField(max_length=40)),
                ('surname1', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Parent_Two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name2', models.CharField(max_length=40)),
                ('surname2', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childs_first_name', models.CharField(max_length=40)),
                ('childs_surname', models.CharField(max_length=40)),
                ('first_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.parent_one')),
                ('second_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.parent_two')),
            ],
        ),
    ]
